# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

# Add/remove 'vélo' label if issue contains the words 'vélo'
vélo:
    - '(vélo)'

vélo:
    - '(velo)'

vélo:
    - '(Velo)'

vélo:
    - '(Vélo)'

vélo:
    - '(cyclisme)'

vélo:
    - '(Cyclisme)'

vélo:
    - '(pédale)'

vélo:
    - '(pédalage)'
