# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

# Add/remove 'vélo' label if issue contains the following words :
vélo:
    - '(pédale)'
    - '(vélo)'
