on:
  issues:
    types: [created, opened, edited, labeled, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
##########
# Dev
##########
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/7"
        column-name: "To do"
        label-name: "github"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/7"
        column-name: "To do"
        label-name: "dev"
        columns-to-ignore: "*"
##########
# SI
##########
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/38"
        column-name: "To do"
        label-name: "sécurité"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/18"
        column-name: "To do"
        label-name: "architecture"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/39"
        column-name: "To do"
        label-name: "architecture data"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/22"
        column-name: "To do"
        label-name: "SharePoint"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/22"
        column-name: "To do"
        label-name: "office365"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/27"
        column-name: "To do"
        label-name: "agilité"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/27"
        column-name: "To do"
        label-name: "ux design"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_TO_PROJECT }}"
        project-url: "https://github.com/orgs/TheFeloDevTeam/projects/18"
        column-name: "To do"
        label-name: "object storage"
        columns-to-ignore: "*"