name: "Set Issue Label archi"
on:
  issues:
    types: [created, opened, edited, labeled, unlabeled, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
########
# archi
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["architecture", "architecte", "rest", "REST", "iam", "IAM"]'
          labels: '["architecture"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"      
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["rest", "post", "hook", "webhook"]'
          labels: '["api"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["JavaScript"]'
          labels: '["JavaScript"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["data lake", "datalake", "hadoop", "map reduce", "data ware", "dataware", "spark", "graphx"]'
          labels: '["data lake"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["big data", "big data"]'
          labels: '["big data"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["storage", "nas", "san", "block storage", "stockage"]'
          labels: '["storage"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["oauth", "token", "Saml"]'
          labels: '["sécurité", "architecture"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["agilité", "user story", "storyboard", "experience map", "blueprint", "epic", "scrum"]'
          labels: '["agilité"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["database", "base de données"]'
          labels: '["database"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["object storage"]'
          labels: '["object storage"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["apache", "hadoop"]'
          labels: '["apache"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
