name: "Set Issue Label sport"
on:
  issues:
    types: [created, opened, edited, labeled, unlabeled, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
########
# SPORT
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["sortie longue", "sorties longues"]'
          labels: '["sortie longue"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["côte", "dénivelé"]'
          labels: '["côte"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["crawl"]'
          labels: '["crawl", "natation", "sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["assouplissement"]'
          labels: '["assouplissement articulations"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["puissance"]'
          labels: '["puissance"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["matériel", "équipement"]'
          labels: '["matériel"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["workout", "entraînement", "fractionné","ppg"]'
          labels: '["entraînement"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# PPG
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["ppg", "pliométrie", "jump"]'
          labels: '["ppg", "sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["squat", "fentes"]'
          labels: '["squats", "ppg", "sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Vélo
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["vélo", "cycliste"]'
          labels: '["vélo"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["home trainer"]'
          labels: '["vélo","HT", "matériel"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["pédalage", "danseuse"]'
          labels: '["technique de pédalage", "vélo"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# CAP
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["cap", "course à pied", "running"]'
          labels: '["cap"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["foulée"]'
          labels: '["cap","foulée"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
