name: "Set Issue Label sport"
on:
  issues:
    types: [created, opened, edited, labeled, unlabeled, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
########
# SPORT
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["sortie longue", "sorties longues"]'
          labels: '["sortie longue"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["côte", "dénivelé"]'
          labels: '["côte"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["crawl"]'
          labels: '["crawl", "natation", "sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["puissance"]'
          labels: '["puissance"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["matériel", "équipement"]'
          labels: '["matériel"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["workout", "entraînement", "fractionné","ppg"]'
          labels: '["entraînement"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# PPG
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["ppg", "pliométrie", "jump"]'
          labels: '["ppg"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["squat", "fentes"]'
          labels: '["squats", "ppg"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Vélo
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["vélo", "cycliste"]'
          labels: '["vélo"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["home trainer"]'
          labels: '["vélo","HT", "matériel"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["pédalage", "danseuse"]'
          labels: '["technique de pédalage", "vélo"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# CAP
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["cap", "course à pied"]'
          labels: '["cap"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["foulée"]'
          labels: '["cap","foulée"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# anatomie
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["assouplissement"]'
          labels: '["assouplissement articulations"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["hanche"]'
          labels: '["hanche"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["bassin"]'
          labels: '["bassin"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["anatomie", "bras", "jambe", "muscle"]'
          labels: '["anatomie"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["genoux", "épaule", "hanche", "bassin", "sacro-iliaque", "coxo-fémorale"]'
          labels: '["articulation"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["dos"]'
          labels: '["dos"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# blessure
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["douleur", "blessure", "pathologie", "douleurs", "blessures", "pathologies", "syndrome"]'
          labels: '["pathologie"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# métabolisme et nutrition
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["métabolisme"]'
          labels: '["métabolisme"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["hydratation"]'
          labels: '["hydratation"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["gel", "isotonique", "glucide", "électrolyte", "alimentation", "calorique", "fruit", "barre"]'
          labels: '["nutrition"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["indice glycémique"]'
          labels: '["indice glycémique", "nutrition"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
