name: "Set Issue Label"
on:
  issues:
    types: [created, opened, edited, labeled, unlabeled, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
########
# Maison, bricolage, vacances
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["maison"]'
          labels: '["maison"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["entretenir", "nettoyage", "nettoyer"]'
          labels: '["entretien"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["ventoux", "aix-en-provence", "sainte-victoire"]'
          labels: '["vacances"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Banque
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["banque", "bancaire"]'
          labels: '["banque"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Management
########
#      - uses: Naturalclar/issue-action@v1.0.0
#        with:
#          keywords: '["gestion", "management", "manager"]'
#          labels: '["manager"]'
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Vidéo
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["youtube.com", "youtu.be"]'
          labels: '["vidéo"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# Dev
########
#      - uses: Naturalclar/issue-action@v1.0.0
#        with:
#          keywords: '["github"]'
#          labels: '["github"]'
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#      - uses: Naturalclar/issue-action@v1.0.0
#        with:
#          keywords: '["actions", "action", "workflow"]'
#          labels: '["actions"]'
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# workspace
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["liste", "list"]'
          labels: '["liste"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["office 365", "SharePoint", "OneNote", "OneDrive", "outlook", "Microsoft flow", "flow.microsoft"]'
          labels: '["office365"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["SharePoint", "sharepoint"]'
          labels: '["SharePoint"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
########
# autres
########
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["qu''est-ce que"]'
          labels: '["définition"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
