name: "Set Issue Label"
on:
  issues:
    types: [created, opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["vélo", "velo", "cycling", "cycliste", "pédale"]'
          labels: '["vélo","sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["cap", "course à pied", "running"]'
          labels: '["cap"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["gel", "isotonique", "glucide", "électrolyte"]'
          labels: '["nutrition"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["big data", "data lake", "datalake", "hadoop", "map reduce", "data ware", "dataware", "bi"]'
          labels: '["big data / data lake"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["github"]'
          labels: '["github"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["actions", "actions"]'
          labels: '["actions"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["sortie longue"]'
          labels: '["sortie longue"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["architecture", "architecte"]'
          labels: '["architecture"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["côte", "dénivelé"]'
          labels: '["côte"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["crawl"]'
          labels: '["crawl"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["squat"]'
          labels: '["squats", "ppg", "sport"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
